apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deploy
    labels:
      tier: frontend
spec:
  replicas: 6
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: nginx-pods
      labels: 
        app: noob-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.18
