apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
      annotations:
        kubernetes.io/change-cause: "Customer Version 1"
    spec:
      containers:
      - name: customer
        image: amigoscode/kubernetes:customer-v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: ORDER_SERVICE
            value: "10.244.0.63:8081"
        ports:
        - containerPort: 8080
