apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment-2025
spec:
  replicas: 2
  selector:
   matchLabels:
     app: customer
     tier: backend
  template:
    metadata:
      name: customer-pod
      labels:
        app: customer
        tier: backend
    spec:
      containers:
        - name: customer-pod
          image: amigoscode/kubernetes:customer-v1
          resources:
            limits:
               memory: "128Mi"
               cpu: "500m"
          env:
            - name: ORDER_SERVICE
              value: "order-service"
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
   type: NodePort
   selector:
       app: customer
       tier: backend
   ports:
      - port: 80
        targetPort: 8080
        nodePort: 30000
