apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    app: frontend
    name: test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
     matchLabels:
        name: hello-world
  template:
    metadata:
       name: hello-world
       labels:
         name: hello-world
       annotations:
         kubernetes.io/change-cause: "Changed image to amigoscode/kubernetes:hello-world-v4"
    spec:
       containers:
          - name: hello-world
            image: amigoscode/kubernetes:hello-world-v4
            resources: 
                limits:
                  memory: "128Mi"
                  cpu: "500m"
            ports:
               - containerPort: 80
