apiVersion: apps/v1
kind: Deployment
metadata:
   name: frontend-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend-pod
      tier: frontend
  template:
    metadata:
      name: frontend-pod
      labels:
        app: frontend-pod
        tier: frontend
    spec:
      containers:
        - name: frontend-container
          image: amigoscode/kubernetes:frontend-v1
          resources:
              limits:
                memory: "500Mi"
                cpu: "128Mi"
         ports:
           - containerPort: 80


---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
   type: LoadBalanacer
   selector:
     app: frontend-pod
     tier: frontend
   ports:
     - port: 80
       targetPort: 80
