apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment-2025
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order
      tier: backend
  template:
      metadata:
        name: order-2025-pods
        labels:
          app: order
          tier: backend
      spec:
         containers:
           - name: order-container
             image: amigoscode/kubernetes:order-v1
             resources:
                limits:
                   memory: "128Mi"
                   cpu: "500m"
             ports:
               - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
   type: ClusterIP
   selector:
        app: order
        tier: backend
   ports:
      - port: 8081
        targetPort: 8081
