apiVersion: apps/v1
kind: Deployment
metadata:
  name: videogamebackdb
spec:
  replicas: 3
  selector:
    matchLabels:
      app: videogamebackdb
  template:
    metadata:
      labels:
        app: videogamebackdb
    spec:
      containers:
      - name: videogamebackdb
        image: acompletenoobsmoke/basedgamenode_dev
        resources:
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        env: 
          - name: MONGO_URL
            value: 'mongodb+srv://baseduser:basedpassword@cluster0.vpxaw.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
          - name: JWT_SECRET
            value: 'somethingverybased'
        ports:
        - containerPort: 8085

---

apiVersion: v1
kind: Service
metadata:
  name: videogamebackdb
spec:
  selector:
    app: videogamebackdb
  ports:
  - port: 80
    targetPort: 8085
    protocol: TCP

---

  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: videogameingress
    labels:
      name: videogameingress
  spec:
    ingressClassName: nginx
    rules:
    - host: www.acompletenoobsmokegamedb.com
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service: 
              name: videogamebackdb
              port: 
                number: 80
  

