apiVersion: apps/v1
kind: Deployment
metadata:
  name: videogamefrontdb
spec:
  selector:
    matchLabels:
      app: videogamefrontdb
  template:
    metadata:
      labels:
        app: videogamefrontdb
    spec:
      containers:
      - name: videogamefrontdb
        image: acompletenoobsmoke/videogamedbfrontend_dev_1:latest
        resources:
          limits:
            memory: "700Mi"
            cpu: "500m"
        env:
          - name: REACT_APP_SERVICE_URL
            value: "acompletenoobsmokegamedb.com"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: videogamefrontdb
spec:
  selector:
    app: videogamefrontdb
  ports:
  - port: 3000
    targetPort: 3000

