apiVersion: v1 
kind: Service 
metadata: 
  name: basic-service-2025
  labels: 
    name: basic-service-2025 
    app: front-end
spec: 
  type: NodePort 
  selector: 
    name: hello-world-noob
    environment: dev
    tier: backend
    department: engineering
  ports: 
    - port: 3000
      targetPort: 3000
      nodePort: 30005