apiVersion: v1
kind: Service
metadata:
  name: customer-node
spec:
  type: NodePort
  selector:
    app: customer
    environment: test
    tier: backend
    department: engineering
  ports:
  - port: 80
    targetPort: 8080
