apiVersion: v1
kind: Service
metadata:
  name: customer-node
  environment: test
  tier: backend
  department: engineering
spec:
  type: NodePort
  selector:
    app: customer
  ports:
  - port: 80
    targetPort: 8080
