apiVersion: batch/v1
kind: CronJob
metadata:
  name: db-backup-cronjob
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
   spec:
    template:
     spec:
       containers:
        - name: backup
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - "echo 'performing db backup...' && sleep 20"
       restartPolicy: Never

