apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  app-name: order
  app-version: 1.0.0
  team: engineering

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }


        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        location /health {
            access_log off;
            return 200 "healthy\n";
        }
    }

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-map-deploy
  labels:
    app: config-map
spec:
  replicas: 2
  selector:
   matchLabels:
    app: config-map
  template:
    metadata:
      name: config-map-pod
      labels:
        app: config-map
    spec:
      volumes:
        - name: order-nginx-config
          configMap:
             name: nginx-conf
        - name: order-app-properties-config
          configMap:
              name: app-properties
        - name: config
          projected:
            sources:
               - configMap:
                    name: nginx-conf
               - configMap:
                    name: app-properties
      containers:
        - name: config-map-container-v1
          image: busybox
          volumeMounts:
             - mountPath: /etc/order/nginx
               name: order-nginx-config
             - name: order-app-properties-config
               mountPath: /etc/order/properties
             - name: config
               mountPath: /etc/order/config
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          command:
             - "/bin/sh"
             - "-c"
          args:
             - "sleep 4000"
        - name: config-map-container-v2
          image: busybox
          resources:
             limits:
               memory: "128Mi"
               cpu: "500m"
          command:
            - "/bin/sh"
            - "-c"
          args:
            - "env && sleep 4000"
          env:
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                   name: app-properties
                   key: app-version
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                   name: app-properties
                   key: app-name
            - name: APP_TEAM
              valueFrom:
                configMapKeyRef:
                   name: app-properties
                   key: team
            - name: NGINX_CONF
              valueFrom:
                configMapKeyRef:
                   name: nginx-conf
                   key: nginx.conf
