apiVersion: v1
kind: Pod
metadata:
   name: cool-pod
   namespace: cool-namespace
   labels:
     tier: frontend
spec:
  containers:
     - name: nginx-test
       image: nginx
       ports:
         - containerPort: 80
