apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: noob-replicas
spec:
   replicas: 2
   selector:
     matchLabels:
        app: frontend
   template:
      metadata:
         name: hello-world
         labels:
           app: frontend
      spec:
        containers:
          - name: hello-world-container
            image: amigoscode/kubernetes:hello-world
            ports:
              - containerPort: 80
