apiVersion: apps/v1
kind: Deployment
metadata:
  name: pull-deploy
  labels:
    apps: secrets
spec:
  replicas: 2
  selector:
   matchLabels:
     apps: secrets
     type: pull
  template:
    metadata:
     name: pull-secrets-pod
     labels:
       apps: secrets
       type: pull
    spec:
      containers:
        - name: pull-container
          image: amigoscode/private
          resources:
             limits:
               memory: "128Mi"
               cpu: "500m"
          ports:
           - containerPort: 80
