apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-deployment
  labels:
    apps: secret
spec:
  replicas: 3
  selector:
   matchLabels:
    apps: secret
  template:
   metadata:
     name: secret-pod
     labels:
      apps: secret
   spec:
    volumes:
      - name: secret-1
        secret:
         secretName: mysecret
    containers:
      - name: secret-container
        image: busybox
        volumeMounts:
           - mountPath: /etc/secrets
             name: secret-1
        env:
          - name: ACOMPLETENOOBSMOKE_SECRET
            valueFrom:
              secretKeyRef:
                 key: secret
                 name: mysecret-from-file
        command:
           - "sleep"
           - "4000"
        resources:
           limits:
              memory: "128Mi"
              cpu: "500m"
